import { User } from './UserTable';

export const dummyTeams: User[] = [
	{
		userId: 1,
		name: 'John Connor',
		email: 'john.connor@gmail.com',
		role: 'Administrator',
		createdAt: '10/4/2022',
	},
	{
		userId: 2,
		name: 'Adam McFadden',
		email: 'adam.mcfadden@bluewave.ca',
		role: 'Member',
		createdAt: '10/4/2022',
	},
	{
		userId: 3,
		name: 'Cris Cross',
		email: 'cris.cross@hotmail.com',
		role: 'Member',
		createdAt: '10/4/2022',
	},
	{
		userId: 4,
		name: 'Prince Evans',
		email: 'prince.evans@bluewave.ca',
		role: 'Member',
		createdAt: '10/4/2022',
	},
	{
		userId: 5,
		name: 'Ava Patel',
		email: 'ava.patel@gmail.com',
		role: 'Administrator',
		createdAt: '11/15/2022',
	},
	{
		userId: 6,
		name: 'Lucas Wong',
		email: 'lucas.wong@bluewave.ca',
		role: 'Member',
		createdAt: '12/20/2022',
	},
	{
		userId: 7,
		name: 'Emma Watson',
		email: 'emma.watson@gmail.com',
		role: 'Member',
		createdAt: '1/10/2023',
	},
	{
		userId: 8,
		name: 'Olivia Hernandez',
		email: 'olivia.hernandez@bluewave.ca',
		role: 'Administrator',
		createdAt: '2/5/2023',
	},
	{
		userId: 9,
		name: 'Noah Bennett',
		email: 'noah.bennett@hotmail.com',
		role: 'Member',
		createdAt: '3/12/2023',
	},
	{
		userId: 10,
		name: 'Mia Turner',
		email: 'mia.turner@bluewave.ca',
		role: 'Member',
		createdAt: '4/25/2023',
	},
	{
		userId: 11,
		name: 'Liam Scott',
		email: 'liam.scott@gmail.com',
		role: 'Administrator',
		createdAt: '5/18/2023',
	},
	{
		userId: 12,
		name: 'Sophia Carter',
		email: 'sophia.carter@bluewave.ca',
		role: 'Member',
		createdAt: '6/30/2023',
	},
	{
		userId: 13,
		name: 'Ethan Adams',
		email: 'ethan.adams@gmail.com',
		role: 'Member',
		createdAt: '7/14/2023',
	},
	{
		userId: 14,
		name: 'Isabella Lee',
		email: 'isabella.lee@bluewave.ca',
		role: 'Administrator',
		createdAt: '8/22/2023',
	},
	{
		userId: 15,
		name: 'James King',
		email: 'james.king@hotmail.com',
		role: 'Member',
		createdAt: '9/9/2023',
	},
	{
		userId: 16,
		name: 'Emily Green',
		email: 'emily.green@gmail.com',
		role: 'Member',
		createdAt: '10/1/2023',
	},
	{
		userId: 17,
		name: 'William Harris',
		email: 'william.harris@bluewave.ca',
		role: 'Administrator',
		createdAt: '11/5/2023',
	},
	{
		userId: 18,
		name: 'Amelia White',
		email: 'amelia.white@gmail.com',
		role: 'Member',
		createdAt: '12/15/2023',
	},
	{
		userId: 19,
		name: 'Mason Baker',
		email: 'mason.baker@hotmail.com',
		role: 'Member',
		createdAt: '1/10/2024',
	},
	{
		userId: 20,
		name: 'Charlotte Rodriguez',
		email: 'charlotte.rodriguez@bluewave.ca',
		role: 'Administrator',
		createdAt: '2/20/2024',
	},
	{
		userId: 21,
		name: 'Henry Clark',
		email: 'henry.clark@gmail.com',
		role: 'Member',
		createdAt: '3/5/2024',
	},
	{
		userId: 22,
		name: 'Scarlett Lewis',
		email: 'scarlett.lewis@bluewave.ca',
		role: 'Member',
		createdAt: '4/10/2024',
	},
	{
		userId: 23,
		name: 'Daniel Walker',
		email: 'daniel.walker@hotmail.com',
		role: 'Administrator',
		createdAt: '5/15/2024',
	},
	{
		userId: 24,
		name: 'Grace Hall',
		email: 'grace.hall@gmail.com',
		role: 'Member',
		createdAt: '6/20/2024',
	},
	{
		userId: 25,
		name: 'Benjamin Young',
		email: 'benjamin.young@bluewave.ca',
		role: 'Member',
		createdAt: '7/25/2024',
	},
];
